# Generated by Django 5.0.6 on 2024-06-23 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Компани")),
                (
                    "company_id",
                    models.CharField(max_length=200, verbose_name="Байгууллагын РД"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "office_id",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Оффис хаяг"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offices",
                        to="Santo.company",
                        verbose_name="Компани",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("Цахилгаан бараа", "Цахилгаан бараа"),
                            ("Тавилга", "Тавилга"),
                            ("Техник төхөөрөмж", "Техник төхөөрөмж"),
                            ("Бусад", "Бусад"),
                        ],
                        default="Цахилгаан бараа",
                        max_length=200,
                        verbose_name="Хөрөнгийн төрөл",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="Хөрөнгийн нэр"),
                ),
                ("rating", models.IntegerField(verbose_name="Үнэлгээ")),
                (
                    "use_time",
                    models.CharField(max_length=50, verbose_name="Ашиглах хугацаа"),
                ),
                ("used_time", models.DateField(verbose_name="Хүлээж авсан огноо")),
                ("quantity", models.IntegerField(verbose_name="Тоо ширхэг")),
                ("explanation", models.TextField(verbose_name="Тайлбар")),
                (
                    "picture",
                    models.ImageField(
                        upload_to="product_images/", verbose_name="Зураг"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="Santo.company",
                        verbose_name="Компани",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="Santo.office",
                        verbose_name="Оффис",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=200, verbose_name="Албан тушаал"),
                ),
                ("firstname", models.CharField(max_length=200, verbose_name="Овог")),
                ("lastname", models.CharField(max_length=100, verbose_name="Нэр")),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Утасны дугаар"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="И-мэйл"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        choices=[
                            ("Хэрэглэгч", "Хэрэглэгч"),
                            ("Онцгой хэрэглэгч", "Онцгой хэрэглэгч"),
                            ("АДМИН", "АДМИН"),
                        ],
                        default="Хэрэглэгч",
                        max_length=50,
                        verbose_name="Эрх",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Нэвтрэх нэр"
                    ),
                ),
                ("password", models.CharField(max_length=200, verbose_name="Нууц үг")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="users",
                        to="Santo.company",
                        verbose_name="Компани",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_date", models.DateField(verbose_name="Шилжүүлэгийн огноо")),
                ("command_id", models.CharField(max_length=200)),
                ("command_date", models.DateField(verbose_name="Тушаалын огноо")),
                (
                    "command_pic",
                    models.ImageField(
                        upload_to="product_images/", verbose_name="Тушаалын зураг"
                    ),
                ),
                (
                    "product_pic",
                    models.ImageField(
                        upload_to="product_images/", verbose_name="Эд хөрөнгийн зураг"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_as_company",
                        to="Santo.company",
                        verbose_name="Компани",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_as_name",
                        to="Santo.product",
                        verbose_name="Нэр",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_as_position",
                        to="Santo.user",
                        verbose_name="Албан тушаал",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_date", models.DateField(verbose_name="Акталсан огноо")),
                (
                    "action_code",
                    models.CharField(
                        max_length=50, verbose_name="Актын тушаалын дугаар"
                    ),
                ),
                (
                    "action_command_date",
                    models.DateField(verbose_name="Актын тушаалын огноо"),
                ),
                (
                    "product_pic",
                    models.ImageField(
                        upload_to="product_images/", verbose_name="Эд хөрөнгийн зураг"
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="Үнэлгээ")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_as_company",
                        to="Santo.company",
                        verbose_name="Компани",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_as_name",
                        to="Santo.product",
                        verbose_name="Нэр",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_as_position",
                        to="Santo.user",
                        verbose_name="Албан тушаал",
                    ),
                ),
            ],
        ),
    ]
